### PR TITLE
py36: re-rendered with conda-smithy 2.1.1

### PR DESCRIPTION
**Pull request by aasensio**

### CODE REVIEW

**Comment by jakirkham** [comment]
Failing because of missing NumPy 1.12 support for `astropy`.

xref: https://github.com/conda-forge/astropy-feedstock/issues/6

**Comment by aasensio** [comment]
Yes, I did some research and arrived to the same conclusion but forgot to comment it.

**Comment by jakirkham** [comment]
I believe the astropy issue is dealt with. Might be worth retrying the re-rendering. Should add that conda-smithy is now at 2.1.1.

**Comment by cdeil** [comment]
Is this PR superseded or complimentary to #4 by @zonka ?
If this should still go in -- is it ready to go or is there some remaining issue?

**Comment by aasensio** [comment]
I would say that this is superseded by #4

**Pull request closed without merging**
