### PR TITLE
Update to version 1.17.1

### PR DESCRIPTION
**Pull request by lpsinger**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by lpsinger** [comment]
@conda-forge-admin, please rerender

**Comment by lpsinger** [comment]
We're going to have to create an unbundled healpix-cxx conda package for this build to succeed.

**Comment by lpsinger** [comment]
I am trying to update https://github.com/conda-forge/healpix_cxx-feedstock and https://github.com/conda-forge/libsharp-feedstock so that we can link against the shared libraries of both of them rather than building our bundled sources for them.

However, I have discovered that there are three different copies of libsharp floating around:

- https://sourceforge.net/p/healpix/code/HEAD/tree/trunk/src/common_libraries/libsharp/
- https://github.com/Libsharp/libsharp (doesn't have pkgconfig files)
- https://gitlab.mpcdf.mpg.de/mtr/libsharp (has pgkconfig files, but has a different library name: `-lsharp2`, not `-lsharp`)

Which of these is the authoritative version now, @mreineck? It seems like the last one is the most recently maintained. Should we use that one, and update healpix-cxx and healpy to link against libsharp2 instead of libsharp?

**Comment by mreineck** [comment]
https://sourceforge.net/p/healpix/code/HEAD/tree/trunk/src/common_libraries/libsharp/ is the authoritative version. This is the one that has been used in the last Healpix releases and is known to work. The second link is an archived repo which is not maintained anymore. The last was meant for potential future improvements, but the functionality has now entirely moved to `ducc0`.

**Comment by lpsinger** [comment]
> https://sourceforge.net/p/healpix/code/HEAD/tree/trunk/src/common_libraries/libsharp/ is the authoritative version. This is the one that has been used in the last Healpix releases and is known to work. The second link is an archived repo which is not maintained anymore. The last was meant for potential future improvements, but the functionality has now entirely moved to `ducc0`.

Is it possible to unbundle it from the monolithic healpix repo and just bring https://github.com/Libsharp/libsharp up to date? It's very annoying packaging code from that Subversion monorepo.

**Comment by mreineck** [comment]
OK, in that case please use the `libsharp_healpix` branch of https://gitlab.mpcdf.mpg.de/mtr/libsharp for the time being. I can try to unarchive the Github repo too, but I don't know yet how complicated that is.

**Comment by mreineck** [comment]
The `libsharp_healpix` branch is now also available at  https://github.com/Libsharp/libsharp. I hope I got everything right.

**Comment by lpsinger** [comment]
> The `libsharp_healpix` branch is now also available at https://github.com/Libsharp/libsharp. I hope I got everything right.

I don't know what to do with this. The Conda package https://github.com/conda-forge/libsharp-feedstock is built from the last release from the master branch of https://github.com/Libsharp/libsharp which contains Python bindings etc.

**Comment by mreineck** [comment]
Sorry, I wasn't aware of the conda package until now and have absolutely no connection to it. All I did was to make the `autotools`-configurable package living at https://sourceforge.net/p/healpix/code/HEAD/tree/trunk/src/common_libraries/libsharp/ available in a standalone fashion (as branch `libsharp_healpix` at  https://github.com/Libsharp/libsharp). Isn't this what you were asking for?

**Comment by lpsinger** [comment]
No. I was hoping that you were going to update https://github.com/Libsharp/libsharp so that we could build healpy against the conda package for libsharp.

**Comment by mreineck** [comment]
I won't be able to do that, as I don't even understand the Python bindings in there - they were made by Dag Sverre Seljebotn, and I'm only familiar with `pybind11` myself.

**Comment by lpsinger** [comment]
> I won't be able to do that, as I don't even understand the Python bindings in there - they were made by Dag Sverre Seljebotn, and I'm only familiar with `pybind11` myself.

Oh, I see. For the record, here are the three variants of libsharp that I am aware of:

- libsharp2 - https://gitlab.mpcdf.mpg.de/mtr/libsharp
- healpix-cxx libsharp - https://sourceforge.net/p/healpix/code/HEAD/tree/trunk/src/common_libraries/libsharp/
- libsharp - https://github.com/Libsharp/libsharp

The last one says, "This repository has been archived and is only kept so that packages depending on it have a canonical [sic] place to download the last version." So of these three it appears that only libsharp2 is currently maintained. Would it be possible to update the healpix-cxx source so that it uses libsharp2 instead of libsharp?

Then I could create Conda packages for libsharp2.

**Comment by mreineck** [comment]
Let's say that both `libsharp2` and its slightly tweaked twin inside `healpix` are on life support - I will fix bugs when found, but there is certainly no active development going on any more. Anyone who wants to use this kind of SHT in new projects should use `ducc0`. I'm more than willing to help with adjusting existing codes and explain its usage.

Are there many projects that would benefit from a standalone `libsharp2` package? And how did they cope so far?
My hope has always been that `libsharp` would be linked statically wherever it is needed, or I would have taken more precautions against `libsharp2` and the version inside the Healpix repo diverging.

**Comment by lpsinger** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
