### PR TITLE
update to 1.10.3

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by jakirkham** [comment]
Needs a [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` 2.3.1.

**Comment by cdeil** [comment]
@zonca @jakirkham - Is this PR ready to go?

Missing healpy conda packages for Python 3.6 and Numpy 1.13 are causing some issues for us in Gammapy (see https://github.com/gammapy/gammapy/pull/1063#issuecomment-308406963) and https://github.com/hipspy/hips (where we want to support only Python 3.6+, but were missing conda packages for healpy for now).

**Comment by zonca** [comment]
I think it worked, @jakirkham can you please crosscheck and merge?
thanks!

**Comment by zonca** [comment]
@jakirkham could you please merge the PR? I'm getting a few requests about an updated conda package.

**Comment by jakirkham** [comment]
I'm not a maintainer on this feedstock and would prefer to yield to the maintainer.

**Comment by jakirkham** [comment]
Would you have time to take a look at this @mwcraig?

**Comment by mwcraig** [comment]
thanks, @zonca, merging! (and thanks for the ping, @jakirkham)

**Comment by cdeil** [comment]
Thanks for this update!

**Comment by zonca** [comment]
@mwcraig thanks for merging, I see only OSX packages updated, how do I check the error log for Linux?

**Comment by mwcraig** [comment]
In the readme on the front page for the repo there is a badge for circe-ci which is where the linux builds are done. Let me know if you need help troubleshooting.

**Comment by mwcraig** [comment]
@zonca -- it looks like some sort of ssh permission issue. 

@conda-forge/core -- any hints on this failed build:

https://circleci.com/gh/conda-forge/healpy-feedstock/7

**Comment by jakirkham** [comment]
Sent you a PM on gitter that should help.

**Comment by mwcraig** [comment]
@zonca -- to update, we hope we've fixed the problem, but if you could check for a linux build in the morning that would be great.

**Comment by zonca** [comment]
Thanks I see all the builds, @cdeil would you have time to test one of the py36 builds?

**Comment by cdeil** [comment]
For me on Mac this one works fine:
```
healpy:    1.10.3-np111py36_0 conda-forge
```
Thanks!

**Comment by cdeil** [comment]
As far as I can see the Python 3.6 builds on travis-ci for the `hips` package (on Mac and Linux) are also now good with the new conda packages built here:
* https://github.com/hipspy/hips/pull/31
* https://travis-ci.org/hipspy/hips/builds/246116649

**Comment by zonca** [comment]
Very good, thanks!

**Pull request merged**
